version: '3.3'

networks:
  postgres:
    driver: bridge

services:

  db:
    image: postgres
    restart: "always"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - postgres

  meilisearch:
    restart: unless-stopped
    image: getmeili/meilisearch:latest
    volumes:
      - /var/local/meilisearch:/data.ms
    ports:
      - "7700:7700"
    networks:
      - postgres

  php:
    restart: "no"
    networks:
      - postgres
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./watchme:/home/watchme

  web:
    restart: "no"
    depends_on:
      - db
      - php
    networks:
      - postgres
    image: nginx:latest
    volumes:
      - ./watchme.conf:/etc/nginx/conf.d/default.conf
      - ./watchme:/home/watchme
    ports:
      - "80:80"

  pgadmin:
    image: dpage/pgadmin4
    restart: "no"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres

volumes:
  db:
  pgadmin:
